insert into attendees (room_id, attendee_name, feedback) values (1, 'methodical', 'Triple-buffered uniform utilisation');
insert into attendees (room_id, attendee_name, feedback) values (2, 'Customizable', 'Quality-focused multimedia neural-net');
insert into attendees (room_id, attendee_name, feedback) values (3, 'extranet', 'Devolved homogeneous hub');
insert into attendees (room_id, attendee_name, feedback) values (4, 'Up-sized', 'Assimilated coherent implementation');
insert into attendees (room_id, attendee_name, feedback) values (5, 'Diverse', 'Automated empowering collaboration');
insert into attendees (room_id, attendee_name, feedback) values (6, 'motivating', 'Enterprise-wide fault-tolerant core');
insert into attendees (room_id, attendee_name, feedback) values (7, 'fault-tolerant', 'Organized zero administration productivity');
insert into attendees (room_id, attendee_name, feedback) values (8, 'Devolved', 'Focused encompassing firmware');
insert into attendees (room_id, attendee_name, feedback) values (9, 'solution-oriented', 'Public-key fault-tolerant algorithm');
insert into attendees (room_id, attendee_name, feedback) values (10, 'Exclusive', 'Balanced bi-directional parallelism');
insert into attendees (room_id, attendee_name, feedback) values (11, 'policy', 'Synchronised coherent time-frame');
insert into attendees (room_id, attendee_name, feedback) values (12, 'regional', 'Horizontal well-modulated knowledge user');
insert into attendees (room_id, attendee_name, feedback) values (13, 'definition', 'Future-proofed user-facing circuit');
insert into attendees (room_id, attendee_name, feedback) values (4, 'Virtual', 'Persistent mobile ability');
insert into attendees (room_id, attendee_name, feedback) values (5, 'toolset', 'Exclusive holistic projection');
insert into attendees (room_id, attendee_name, feedback) values (6, 'Digitized', 'Focused systematic help-desk');
insert into attendees (room_id, attendee_name, feedback) values (7, 'Synergized', 'Persistent composite knowledge user');
insert into attendees (room_id, attendee_name, feedback) values (8, 'object-oriented', 'Persistent empowering service-desk');
insert into attendees (room_id, attendee_name, feedback) values (9, 'Profit-focused', 'Cross-platform local info-mediaries');
insert into attendees (room_id, attendee_name, feedback) values (10, 'Cross-group', 'Reduced grid-enabled encoding');
insert into attendees (room_id, attendee_name, feedback) values (13, 'monitoring', 'Reactive object-oriented forecast');
insert into attendees (room_id, attendee_name, feedback) values (2, 'web-enabled', 'Ameliorated radical capacity');
insert into attendees (room_id, attendee_name, feedback) values (3, 'open architecture', 'Grass-roots disintermediate approach');
insert into attendees (room_id, attendee_name, feedback) values (4, 'Reactive', 'Profound eco-centric core');
insert into attendees (room_id, attendee_name, feedback) values (5, 'eco-centric', 'Quality-focused national instruction set');
insert into attendees (room_id, attendee_name, feedback) values (6, 'Cross-group', 'Team-oriented optimal instruction set');
insert into attendees (room_id, attendee_name, feedback) values (7, 'intangible', 'Enterprise-wide stable utilisation');
insert into attendees (room_id, attendee_name, feedback) values (8, 'initiative', 'Front-line user-facing workforce');
insert into attendees (room_id, attendee_name, feedback) values (9, 'emulation', 'Horizontal 24 hour pricing structure');
insert into attendees (room_id, attendee_name, feedback) values (10, 'Front-line', 'Horizontal needs-based challenge');
insert into attendees (room_id, attendee_name, feedback) values (11, 'client-server', 'Digitized high-level infrastructure');
insert into attendees (room_id, attendee_name, feedback) values (2, 'function', 'Persevering high-level system engine');
insert into attendees (room_id, attendee_name, feedback) values (3, 'Right-sized', 'Organic zero defect projection');
insert into attendees (room_id, attendee_name, feedback) values (4, 'stable', 'Customizable transitional access');
insert into attendees (room_id, attendee_name, feedback) values (5, 'capacity', 'Persistent 4th generation capacity');
insert into attendees (room_id, attendee_name, feedback) values (6, 'attitude', 'Virtual bottom-line application');
insert into attendees (room_id, attendee_name, feedback) values (7, 'encoding', 'Horizontal scalable algorithm');
insert into attendees (room_id, attendee_name, feedback) values (8, 'pricing structure', 'Optimized logistical system engine');
insert into attendees (room_id, attendee_name, feedback) values (9, 'Open-architected', 'Profit-focused neutral analyzer');
insert into attendees (room_id, attendee_name, feedback) values (10, 'synergy', 'Vision-oriented neutral neural-net');