DROP TABLE IF EXISTS teachers CASCADE;
CREATE TABLE teachers(
    id SERIAL PRIMARY KEY NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    user_password VARCHAR(255) NOT NULL
    email VARCHAR(255) NOT NULL,
);